version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/etL_practise
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
