version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   - mongo
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app

  # mongo:
  #   image: mongo
  #   ports:
  #     - "27017:27017"
